POST http://localhost:8000/users/login
Content-Type: application/json

{
    "name": "1",
    "password": "123456"
}

###

POST https://ricos-backend.herokuapp.com/users/login
Content-Type: application/json

{
    "name": "1",
    "password": "123456"
}


###

POST http://localhost:8000/users/post
Content-Type: application/json

{
    "firstName": "11212",
    "lastName": "123456",
    "username": "12121",
    "mail": "1",
    "password": "1"
}

###

POST http://localhost:8000/users/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMSIsIm1haWwiOiIxIiwiZmlyc3ROYW1lIjoiMSIsImxhc3ROYW1lIjoiMSIsImlhdCI6MTYzMTYxNTMyN30.hPbrezGSS92U7-K0PdMu1R8L7Zn7a3PTnxOl6BUAwZE
Content-Type: application/json

{
    "uid": "1"
}

###

DELETE http://localhost:8000/users/unfollow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMSIsIm1haWwiOiIxIiwiZmlyc3ROYW1lIjoiMSIsImxhc3ROYW1lIjoiMSIsImlhdCI6MTYzMTYxNTMyN30.hPbrezGSS92U7-K0PdMu1R8L7Zn7a3PTnxOl6BUAwZE
Content-Type: application/json

{
    "uid":"2"
}

###

GET http://localhost:8000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMSIsIm1haWwiOiIxIiwiZmlyc3ROYW1lIjoiMSIsImxhc3ROYW1lIjoiMSIsImlhdCI6MTYzMTYxNTMyN30.hPbrezGSS92U7-K0PdMu1R8L7Zn7a3PTnxOl6BUAwZE

### 

GET http://localhost:8000/users/main
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMSIsIm1haWwiOiIxIiwiZmlyc3ROYW1lIjoiMSIsImxhc3ROYW1lIjoiMSIsImlhdCI6MTYzMTYxNTMyN30.hPbrezGSS92U7-K0PdMu1R8L7Zn7a3PTnxOl6BUAwZE

###

GET http://localhost:8000/users/self/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMSIsIm1haWwiOiIxIiwiZmlyc3ROYW1lIjoiMSIsImxhc3ROYW1lIjoiMSIsImlhdCI6MTYzMTYxNTMyN30.hPbrezGSS92U7-K0PdMu1R8L7Zn7a3PTnxOl6BUAwZE

###

GET http://localhost:8000/users/1/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMSIsIm1haWwiOiIxIiwiZmlyc3ROYW1lIjoiMSIsImxhc3ROYW1lIjoiMSIsImlhdCI6MTYzMTYxNTMyN30.hPbrezGSS92U7-K0PdMu1R8L7Zn7a3PTnxOl6BUAwZE

###

POST http://localhost:8000/recipes/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMSIsIm1haWwiOiIxIiwiZmlyc3ROYW1lIjoiMSIsImxhc3ROYW1lIjoiMSIsImlhdCI6MTYzMTYxNTMyN30.hPbrezGSS92U7-K0PdMu1R8L7Zn7a3PTnxOl6BUAwZE

{
    "rid": 1
}

###

GET http://localhost:8000/recipes/getcomments/1

###

POST http://localhost:8000/recipes/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoiMSIsIm1haWwiOiJqYW5lZG9lQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkphbmUiLCJsYXN0TmFtZSI6IkRvZSIsImlhdCI6MTY0NzQyODM3NH0.TumLDJeO436tCYnkJ0KbTy-aarnn_xu0iNoLSvkGMSo

{
    "title": "1",
    "description": "1",
    "ingredients": [{"amount": 1, "unit":"cup","ingredient":"avcoado"}],
    "steps": ["1",2,3],
    "img": "1"
}

###

POST http://localhost:8000/recipes/comments/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsInVzZXJuYW1lIjoiMiIsIm1haWwiOiIyQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikdlb3JnZSIsImxhc3ROYW1lIjoiQnVzaCIsImlhdCI6MTY0NzE4OTM4OX0.sidZFYI8DrbCVzB-HUBAtdAYb79nNRxZRiOz22t8YsE

{
    "rid": 1,
    "content": "Yummy Yummyyyyyyy"
}